"""Game constants for Danger Rose.

This module contains all game constants used throughout the application.
Constants are organized by category for easy access and maintenance.
"""

# Screen Configuration
# SCREEN_WIDTH = 1920
# SCREEN_HEIGHT = 1080
SCREEN_WIDTH = 1280
SCREEN_HEIGHT = 720
FPS = 60

# Window Settings
WINDOW_TITLE = "Danger Rose"
FULLSCREEN_DEFAULT = False

# Sprite Dimensions
SPRITE_SHEET_SIZE = 1024  # Full sprite sheet is 1024x1024
SPRITE_FRAME_WIDTH = 256  # Individual frame width
SPRITE_FRAME_HEIGHT = 341  # Individual frame height
SPRITE_DISPLAY_SIZE = 128  # Display size for sprites in-game
SPRITE_GRID_COLS = 4  # Number of columns in sprite sheet
SPRITE_GRID_ROWS = 3  # Number of rows in sprite sheet

# Animation Timings (in milliseconds)
ANIMATION_DEFAULT_DURATION = 100  # Default frame duration
ANIMATION_IDLE_DURATION = 200  # Idle animation frame duration
ANIMATION_WALK_DURATION = 100  # Walk animation frame duration
ANIMATION_ATTACK_DURATION = 50  # Attack animation frame duration
ANIMATION_HURT_DURATION = 150  # Hurt animation frame duration
ANIMATION_VICTORY_DURATION = 120  # Victory animation frame duration

# Animation Frame Counts
ANIMATION_IDLE_FRAMES = 4
ANIMATION_WALK_FRAMES = 8
ANIMATION_JUMP_FRAMES = 3
ANIMATION_ATTACK_FRAMES = 6
ANIMATION_HURT_FRAMES = 2
ANIMATION_VICTORY_FRAMES = 8

# Game Physics
GRAVITY = 800.0  # Pixels per second squared
JUMP_VELOCITY = -500.0  # Initial jump velocity
PLAYER_SPEED = 300.0  # Player movement speed
PLAYER_ACCELERATION = 1200.0  # Player acceleration
FRICTION = 0.85  # Movement friction coefficient

# UI Constants
BUTTON_WIDTH = 200
BUTTON_HEIGHT = 60
BUTTON_PADDING = 20
MENU_TRANSITION_SPEED = 5.0  # Seconds for menu transitions

# Colors (RGB)
COLOR_BLACK = (0, 0, 0)
COLOR_WHITE = (255, 255, 255)
COLOR_BLUE = (60, 100, 180)
COLOR_GREEN = (60, 180, 100)
COLOR_RED = (180, 60, 60)
COLOR_YELLOW = (220, 200, 60)
COLOR_PURPLE = (180, 60, 180)
COLOR_BROWN = (101, 67, 33)

# Scene Names
SCENE_TITLE = "title"
SCENE_CHARACTER_SELECT = "character_select"
SCENE_HUB_WORLD = "hub_world"
SCENE_SKI_GAME = "ski_game"
SCENE_POOL_GAME = "pool_game"
SCENE_VEGAS_GAME = "vegas_game"
SCENE_DRIVE_GAME = "drive_game"
SCENE_SETTINGS = "settings"
SCENE_PAUSE = "pause"
SCENE_LEADERBOARD = "leaderboard"
SCENE_NAME_ENTRY = "name_entry"

# Audio Settings
DEFAULT_MASTER_VOLUME = 0.7
DEFAULT_MUSIC_VOLUME = 0.5
DEFAULT_SFX_VOLUME = 0.8
AUDIO_FADE_TIME = 500  # Milliseconds for audio fade

# File Paths
CONFIG_FILE = "game_settings.json"
SAVE_FILE = "game_save.json"
HIGH_SCORES_FILE = "high_scores.json"

# Debug Settings
DEBUG_SHOW_FPS = False
DEBUG_SHOW_HITBOXES = False
DEBUG_SHOW_GRID = False

# Game-specific Colors (RGB)
COLOR_SKY_BLUE = (135, 206, 235)
COLOR_SNOW_WHITE = (240, 240, 255)
COLOR_SNOW_ALT = (230, 230, 250)
COLOR_GOLD = (255, 215, 0)
COLOR_NIGHT_SKY = (20, 10, 40)
COLOR_NIGHT_PURPLE = (40, 20, 60)
COLOR_BUILDING_DARK = (30, 15, 50)
COLOR_STREET_GRAY = (50, 50, 50)
COLOR_STREET_LINE = (200, 200, 0)
COLOR_WATER_SPLASH = (100, 150, 255)
COLOR_PLACEHOLDER = (255, 0, 255)  # Magenta for missing assets
COLOR_OVERLAY_GRAY = (200, 200, 200)
COLOR_BOSS_HEALTH = (255, 100, 100)

# Player Movement Constants
PLAYER_SKI_SPEED = 5
PLAYER_SKI_DIAGONAL_SPEED = 3.5
PLAYER_VEGAS_JUMP_POWER = -15
PLAYER_VEGAS_GRAVITY = 0.8
PLAYER_VEGAS_MAX_FALL_SPEED = 12
PLAYER_INVINCIBILITY_DURATION = 2.0  # seconds
PLAYER_HIT_FLASH_DURATION = 0.5
PLAYER_ATTACK_COOLDOWN = 0.5

# Collision Constants
PLAYER_COLLISION_WIDTH = 48
PLAYER_COLLISION_HEIGHT = 48
PLAYER_COLLISION_OFFSET = 24
PLAYER_COLLISION_SIZE = 64
PLAYER_VEGAS_COLLISION_WIDTH = 64
PLAYER_VEGAS_COLLISION_HEIGHT = 100

# Game Timings
GAME_DURATION = 60.0  # Standard game duration in seconds
SKI_CRASH_DURATION = 0.5
POOL_RELOAD_TIME = 0.5
POOL_RELOAD_DURATION = 2.0
POOL_AMMO_CAPACITY = 5
TARGET_SPAWN_INTERVAL = 3.0
POWERUP_SPAWN_INTERVAL = 12.0
POWERUP_FIRST_SPAWN_TIME = 8.0  # Spawn after 8 seconds

# UI Layout Constants
UI_TIMER_PADDING = 20
UI_TIMER_BORDER = 10
UI_HEART_SIZE = 40
UI_HEART_SPACING = 10
UI_SCORE_PADDING = 20
UI_INSTRUCTION_LINE_HEIGHT = 40
UI_INSTRUCTION_START_Y = 350
UI_BIG_TEXT_Y = 200
UI_POWERUP_DISPLAY_X = 250
UI_POWERUP_ITEM_HEIGHT = 50
UI_POWERUP_ICON_SIZE = 15
UI_POWERUP_BAR_WIDTH = 150
UI_POWERUP_BAR_HEIGHT = 8

# Pool Game Constants
POOL_BALLOON_RADIUS = 8
POOL_BALLOON_LAUNCH_SPEED = 800
POOL_BALLOON_UPWARD_ARC = 300
POOL_BALLOON_TRAIL_LENGTH = 10
POOL_BALLOON_HOMING_STRENGTH = 300.0
POOL_BALLOON_MAX_SPEED = 1000.0
POOL_BALLOON_HOMING_RANGE = 300
POOL_SPLASH_PARTICLE_COUNT = 12
POOL_SPLASH_DURATION = 0.5
POOL_SPLASH_BASE_SPEED = 100
POOL_SPLASH_SPEED_VARIANCE = 50
POOL_SPLASH_GRAVITY = 300
POOL_SPLASH_SHRINK_RATE = 0.95
POOL_POOL_MARGIN = 100  # Margin from screen edge for pool
POOL_POOL_BOTTOM_MARGIN = 250
POOL_WATER_WAVE_SPACING = 40
POOL_WATER_WAVE_AMPLITUDE = 5
POOL_WATER_WAVE_FREQUENCY = 0.05
POOL_WATER_SPEED = 50
POOL_WATER_ALPHA = 100
POOL_TRIPLE_SHOT_SPREAD = 15  # degrees
POOL_MAX_TARGETS = 8
POOL_MAX_POWERUPS = 2

# Ski Game Constants
SKI_SCROLL_SPEED = 200
SKI_SNOWFLAKE_POINTS = 10
SKI_MAX_LIVES = 3
SKI_SNOW_PARTICLE_COUNT = 200
SKI_DAD_OFFSET_X = 150
SKI_PLAYER_Y_OFFSET = 200

# Vegas Game Constants
VEGAS_LEVEL_WIDTH = 3000
VEGAS_GROUND_OFFSET = 100
VEGAS_BOSS_ARENA_OFFSET = 640
VEGAS_BOSS_START_Y = 300
VEGAS_BOSS_ATTACK_RANGE = 150
VEGAS_BOSS_DAMAGE = 1
VEGAS_FAR_BG_PARALLAX = 0.3
VEGAS_NEAR_BG_PARALLAX = 0.6
VEGAS_STAR_COUNT = 100
VEGAS_BUILDING_WIDTHS = [150, 150, 150, 150, 150, 150]
VEGAS_BUILDING_HEIGHTS = [200, 300, 250, 280, 320, 240]
VEGAS_BUILDING_SPACING = 20
VEGAS_VICTORY_SCORE_BASE = 1000
VEGAS_VICTORY_HEALTH_BONUS = 500

# Font Sizes
FONT_SMALL = 36
FONT_LARGE = 72
FONT_HUGE = 96

# Overlay Alpha Values
OVERLAY_PAUSE_ALPHA = 128
OVERLAY_GAME_OVER_ALPHA = 180

# Animation Flash Timings
FLASH_INVINCIBILITY_RATE = 10  # Flashes per second
FLASH_HIT_RATE = 20  # Flashes per second
FLASH_POWERUP_WARNING_TIME = 2.0  # Seconds before powerup expires
FLASH_POWERUP_WARNING_RATE = 4  # Flashes per second
